create table guestbook (
	id int not null generated by default as identity,
	created varchar(20),
	updated varchar(20),
	published varchar(20),
	status varchar(255),
	created_by varchar(255),
	updated_by varchar(255),
	published_by varchar(255),
	title varchar(255),
	content clob,
	name varchar(255),
	email varchar(255),
	website varchar(255),
	company varchar(255),
	primary key (id)
)

create table tempconfig (
        configname varchar(255) not null unique,
        configvalue varchar(255),
        primary key (configname)
)

insert into tempconfig select config.name as configname, config.value as configvalue from config

drop table config

rename table tempconfig to config

update config set configvalue='2.1' where configname='database_version'

